### ISSUE TITLE
__HoldingKeyToKey__

### ISSUE THREAD

**Issue by gogonkt** [k0kubun/xremap#18]
Hi, dear k0kubun san!
Very happy to found this great maricle wonder!
I love karabiner, but MBP broken yesterday Orz…, I have to go back my basement -- Archlinux, but I still miss great keyboard remap :P…… bla bla
You great work make me very happy, Thank you! Thank you! and Thank you!
Well! My Ask is can I use __HoldingKeyToKey__ ? I wanna https://gist.github.com/emory/4c0aa3b41958f8960c95 this maping, May I?

all the best!
gogonkt

**Comment by k0kubun** [comment]
Unfortunately, no. (It'll be a superset of https://github.com/k0kubun/xremap/issues/12)

That's because, while I use such features when using a laptop, all laptops I currently use are MacBooks and I use Linux in only a desktop machine. So I have no motivation to implement it yet. I know your feeling well. Very sorry. :sob:

**Comment by k0kubun** [comment]
As this question is already solved, closing
