### ISSUE TITLE
Run when launching X server?

### ISSUE THREAD

**Issue by tgy** [k0kubun/xremap#190]
How would you run xremap when launching the X server (after `startx`)?

Would you add it to the `.xinitrc`? Could you provide an example?

I can then add it the doc in a PR if you want.

I don't understand how it works exactly because xremap seems to be hanging when I run it from my terminal, should it be ran as a daemon process?

All of this is not clear to me when I read the doc.

Thanks

**Comment by k0kubun** [comment]
> xremap seems to be hanging when I run it from my terminal, should it be ran as a daemon process?

Exactly. I'm not against introducing an option like `--daemon` to demonize itself if there's any user of it, but simply implementing it as a foreground process and letting an initd (e.g. systemd) manage it are generally more useful in many ways. For example, I use systemd so that journald automatically manages logs with rotation and systemd restarts xremap automatically in case something unexpected happens.

Example config for systemd is:

```sh
# ~/.config/systemd/user/xremap.service
[Unit]
Description=xremap

[Service]
Restart=always
ExecStart=xremap /path/to/config/xremap.yml --watch`
```

I think (I haven't confirmed it because I don't directly run startx these days) you can start it with `systemd --user start xremap` from `.xinitrc`.
