### ISSUE TITLE
[Feature Request] Is there any plan to support Hyprland

### ISSUE THREAD

**Issue by chenzaichun** [k0kubun/xremap#215]

**Comment by k0kubun** [comment]
Hyperland seems wlroots-based, so as soon as xremap switches the Sway support to general wlroots support, it would be solved at the same time. We already have an issue for it https://github.com/k0kubun/xremap/issues/141, so I'll close this one as a duplication. I can't guarantee when it'll happen since I'm currently working on a relatively large implementation for another project, but I'll review any pull request for it as soon as it's filed.

**Comment by k0kubun** [comment]
Just note that I'm only talking about `application` filter. Every other feature should be already working on Hyperland too.

**Comment by chenzaichun** [comment]
Which version should be used with Hyprland. I've tried sway version, but failed.
