### ISSUE TITLE
Dump current modmap

### ISSUE THREAD

**Issue by haasn** [k0kubun/xremap#283]
`xmodmap -pke` can be used to generate an `~/.Xmodmap` file from the currently active keymap.

Is it possible to add an equivalent to `xmodmap`, which would generate a config file that I can then use as a base for modification / load on wayland?

**Comment by k0kubun** [comment]
X has a concept of a keyboard layout and I assume `xmodmap -pke` would be extracting it, but xremap operates in a lower layer than that, which is why it works for Wayland as is. 

I agree it'd be useful, but I think it'd be better to make that a separate tool that generates a YAML file that can be used with xremap, rather than incorporating the feature to xremap. It'd make things simpler for both tools.

I would welcome anybody to come here and share it once created, but in the meantime, let me close this issue since it's out of scope in this repository.
