### ISSUE TITLE
Permission denied (os error 13)

### ISSUE THREAD

**Issue by TimmermanV** [k0kubun/xremap#430]
Hi,

I downloaded the release binary 0.8.14 (xremap-linux-x86_64-gnome.zip) and I'm facing this error message at the moment when running:
`Error: Failed to prepare an output device: Permission denied (os error 13)`
Right now, the executable is in my Downloads folder, but I did mess about, putting it in `/usr/local/bin`, copying it there using sudo. I have the feeling that somehow messed things up, but even with a freshly downloaded copy I get the same error.
If I run using sudo, xremap does work, but that wasn't required when I just downloaded it.
Any help would be appreciated. And where would I normally place this executable?

I'm on Pop!_OS 22.04 LTS (which uses gnome and X11).

Thanks,
Tim

**Comment by k0kubun** [comment]
If you use X11 GNOME, I strongly encourage you to use xremap-linux-x86_64-x11 instead. The gnome binary is primarily for GNOME Wayland users. The x11 binary hopefully won't require extra setup for sudo-less execution.

**Comment by TimmermanV** [comment]
Thank you for your response. I tried that executable but that shows the same error message unfortunately. I'm pretty sure I did not have permission errors when I first tried xremap, so I think something must have happened when I made that copy as root using sudo. Are there any temporary files that might be lingering around that cannot be overwritten?

**Comment by k0kubun** [comment]
Ah right, the error message was actually not relevant to what variant you chose.

I think your udev rules are misconfigured. Please read README again around "If you want to run xremap without sudo, click here".

**Comment by TimmermanV** [comment]
That did the trick, thank you. So should I still be able to copy xremap to `/usr/local/bin` and run it from there or do you recommend a different location?

**Comment by Konfekt** [comment]
Just for elucidation: How come that despite misconfigured udev rules, X11 analogs like xbindkeys and xcape do not require root permissions? Would you mind adding a note on the security impact of `echo 'KERNEL=="uinput", GROUP="input", TAG+="uaccess"' | sudo tee /etc/udev/rules.d/input.rules` ? Since keyboard input is somewhat sensitive, that would be reassuring

**Comment by k0kubun** [comment]
Because such tools operate on X11 events. 

It's a trade-off. Even if you're on an X11-only environment like X11 GNOME, some places don't go through X11 key events for some reason. Operating on something closer to the device allows you to remap everything.

As to the security impact, only one process can grab a device, so as long as you use xremap, there should be no side impact.
