### ISSUE TITLE
Add Support for Mac Os / Windows

### ISSUE THREAD

**Issue by andrey-mouk** [k0kubun/xremap#96]
First of all thank you for this software. I wish it had support for Mac Os / Windows. I like to hop between multiple operating systems, so I would like to have one tool. Is it possible to implement it? 

For some reason it does not compile on Mac Os (it says there is error in compiling `evdev`),

**Comment by k0kubun** [comment]
Everything underneath xremap is not compatible with macOS and Windows. Supporting macOS or Windows would need to rewrite the entire stack except for CLI and the config parser, so there's little motivation to do so.

For your information, I use [Karabiner-Elements](https://karabiner-elements.pqrs.org/) for macOS and [nodoka](https://appletllc.com/web/nodoka-readme-en.htm) for Windows. Since I'm totally happy with them, it's unlikely that I'll pay the effort to implement and maintain the support on those platforms.
